### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by dov-yih** [dov-yih/speech-registration#1]
List:
+ [x] index page.
+ [x] login feature.
+ [x] user self list.
+ [x] submit new speech.
+ [x] change password.
+ [x] profile & setting page.

next version:
+ [ ] add a teachers table
+ [ ] super user
+ [ ] markdown support 
+ [ ] start speeches

**Comment by yidafu** [comment]
GOOD!!

Now I succeeded in importing JSONAPI and react-redux

**Comment by yidafu** [comment]
Problem: index page -> navbar -> navitem, its active class not right.
